FROM mcr.microsoft.com/playwright:focal

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn cache clean && yarn install
RUN yarn playwright install chromium

COPY . .

RUN yarn build

CMD [ "yarn", "start" ]
