FROM node:latest

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn cache clean && yarn install
RUN yarn playwright install

COPY . .

RUN  chown -R node /usr/src/app
USER node

CMD [ "yarn", "build"]
