version: "3.9"

services:
    mongo:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
        - ./mongodb.conf:/etc/mongo/mongodb.conf
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
        - ./.env:/docker-entrypoint-initdb.d/.env
      command: mongod --config /etc/mongo/mongodb.conf && npm install dotenv
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-defaul_value}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-defaul_value}
        sslTunnelUsername: NONE
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
        ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/
        ME_CONFIG_BASICAUTH: false
    # app:
    #     build:
    #       context: .
    #       dockerfile: Dockerfile.dev
    #     command: yarn start
    #     ports:
    #       - "3000:3000"
    #     working_dir: /src
    #     volumes:
    #       - .:/src
    #     depends_on:
    #       - mongodb

volumes:
  mongodb_data:
  
